"""fix_relationships_and_fks

Revision ID: 9040034cc6f3
Revises: ff3ff5711678
Create Date: 2026-08-26 14:57:16.484431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9040034cc6f3'
down_revision: Union[str, Sequence[str], None] = 'ff3ff5711678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
